os: linux

language: node_js

node_js: 10

cache: yarn

install: yarn --frozen-lockfile

script:
  - yarn lint
  - yarn test

before_deploy:
  - yarn build
  - cd dist/ngx-http-configure

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_token: $NPM_API_KEY
  skip_cleanup: true
  on:
    tags: true
