dist: trusty
sudo: false
language: node_js
node_js:
  - '10'
cache: yarn
install: yarn
script:
  - yarn lint
  - yarn test
after_success:
  - yarn build
before_deploy:
  - cd dist/ngx-http-configure
deploy:
  provider: npm
  email: d_rivas@outlook.com
  skip_cleanup: true
  api_key: $NPM_API_KEY
  on:
    branch: master
    tags: true
    repo: drivas/ngx-http-configure
